---
spring:
  application:
    name: hello-server

server:
  port: 4041

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4040/eureka/
  instance:
    hostname: localhost