---
spring:
  application:
    name: hello-client

server:
  port: 4042

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4040/eureka/
  instance:
    hostname: localhost